apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamify-backend
  namespace: streamify
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamify-backend
  template:
    metadata:
      labels:
        app: streamify-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5001"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: streamify-backend
        image: phamkhanhduy/streamify-backend:3fa3ad32a4efbd8131410c81ba2cd2828a7bc16a
        imagePullPolicy: Always 
        ports:
        - containerPort: 5001
          name: http
        envFrom:
        - configMapRef:
            name: streamify-config
        - secretRef:
            name: streamify-secrets
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi