apiVersion: v1
kind: Service
metadata:
  name: streamify-backend-svc
  namespace: streamify
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
    prometheus.io/scrape: "true"
    prometheus.io/port: "5001"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: streamify-backend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001