apiVersion: v1
kind: Service
metadata:
  name: streamify-backend-svc
  namespace: streamify
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
spec:
  selector:
    app: streamify-backend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001