apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamify-frontend
  namespace: streamify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamify-frontend
  template:
    metadata:
      labels:
        app: streamify-frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      containers:
      - name: streamify-frontend
        image: phamkhanhduy/streamify-frontend:latest
        imagePullPolicy: Always  
        ports:
        - containerPort: 80
          name: http
          hostPort: 5173
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi