apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamify-ingress
  namespace: streamify
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  ingressClassName: nginx
  rules:
    - host: streamifyapp.id.vn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: streamify-frontend-svc
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: streamify-backend-svc
                port:
                  number: 5001