apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: streamify-backend-monitor
  namespace: monitoring 
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: streamify-backend
  namespaceSelector:
    matchNames:
      - streamify
  endpoints:
    - port: http
      path: /metrics
      interval: 15s